//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka_Otomasyon_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisanlar
    {
        public int calisanID { get; set; }
        public string c_TcNo { get; set; }
        public string c_SicilNo { get; set; }
        public string c_Ad { get; set; }
        public string c_Soyad { get; set; }
        public System.DateTime c_DogumTarihi { get; set; }
        public string c_DıgumYeri { get; set; }
        public decimal c_Maas { get; set; }
        public Nullable<decimal> c_Prim { get; set; }
        public int c_Rolid { get; set; }
        public string c_Sifre { get; set; }
    
        public virtual Roller Roller { get; set; }
    }
}
