//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka_Otomasyon_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kkart_Hesaplari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kkart_Hesaplari()
        {
            this.islemler_KrediHesaplari = new HashSet<islemler_KrediHesaplari>();
        }
    
        public long KkartID { get; set; }
        public string KkartHesapNo { get; set; }
        public string KkartIban { get; set; }
        public decimal Kkart_Limit { get; set; }
        public Nullable<decimal> Kkart_Borc { get; set; }
        public string HesapSahipTcno { get; set; }
        public int HesapKesimGunu { get; set; }
        public int SonOdemeGunu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<islemler_KrediHesaplari> islemler_KrediHesaplari { get; set; }
        public virtual Musteriler Musteriler { get; set; }
    }
}
