//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka_Otomasyon_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteriler()
        {
            this.Banka_Hesaplari = new HashSet<Banka_Hesaplari>();
        }
    
        public int müsteriID { get; set; }
        public string MusteriNo { get; set; }
        public string m_TcNo { get; set; }
        public string m_Ad { get; set; }
        public string m_Soyad { get; set; }
        public System.DateTime m_DogumTarihi { get; set; }
        public string m_DogumYeri { get; set; }
        public int m_Rolid { get; set; }
        public string m_Sifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Banka_Hesaplari> Banka_Hesaplari { get; set; }
        public virtual Roller Roller { get; set; }
    }
}
