//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka_Otomasyon_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vislemler_Banka
    {
        public decimal islemTutari { get; set; }
        public string islemAciklama { get; set; }
        public System.DateTime islemTarihi { get; set; }
        public string KategoriAd { get; set; }
    }
}
