//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka_Otomasyon_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banka_Hesaplari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Banka_Hesaplari()
        {
            this.islemler_BankaHesaplari = new HashSet<islemler_BankaHesaplari>();
        }
    
        public int HesapID { get; set; }
        public string BankaHesapNo { get; set; }
        public string BankIban { get; set; }
        public decimal Hesap_Bakiye { get; set; }
        public string HesapSahipTcno { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<islemler_BankaHesaplari> islemler_BankaHesaplari { get; set; }
    }
}
