//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka_Otomasyon_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class islemler_BankaHesaplari
    {
        public int islemID { get; set; }
        public string HesapNo { get; set; }
        public decimal islemTutari { get; set; }
        public string islemAciklama { get; set; }
        public int islemKategori_id { get; set; }
        public System.DateTime islemTarihi { get; set; }
    
        public virtual Banka_Hesaplari Banka_Hesaplari { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
    }
}
